-- V_SAVING
CREATE VIEW V_SAVING AS
SELECT * FROM T_ACCOUNT
INNER JOIN T_SAVING
USING(ACCOUNT_ID);
-- V_BILLING
CREATE VIEW V_BILLING AS
SELECT * FROM T_CARD
INNER JOIN T_BILLING
USING(CARD_ID);
-- V_SAVING2
CREATE VIEW V_SAVING2 AS
SELECT DATECOLUMNS,T_ACCOUNT.ACCOUNT_ID,ACCOUNT_NAME,IFNULL(SAVING_AMOUNT,(SELECT SAVING_AMOUNT FROM T_SAVING WHERE T_SAVING.ACCOUNT_ID = T_ACCOUNT.ACCOUNT_ID AND SAVING_DATE = (SELECT MAX(SAVING_DATE) FROM T_SAVING WHERE T_SAVING.ACCOUNT_ID = T_ACCOUNT.ACCOUNT_ID))) AS "SAVING_AMOUNT",SAVING_DATETIME
FROM V_DATE 
LEFT OUTER JOIN T_ACCOUNT 
LEFT OUTER JOIN T_SAVING 
ON T_SAVING.SAVING_DATE = V_DATE.DATECOLUMNS 
AND T_ACCOUNT.ACCOUNT_ID = T_SAVING.ACCOUNT_ID 
ORDER BY DATECOLUMNS DESC;
-- V_BILLING2
CREATE VIEW V_BILLING2 AS
SELECT DATECOLUMNS,T_CARD.CARD_ID,CARD_NAME,IFNULL(BILLING_AMOUNT,0) AS "BILLING_AMOUNT",BILLING_DATETIME
FROM V_DATE 
LEFT OUTER JOIN T_CARD 
LEFT OUTER JOIN T_BILLING 
ON T_BILLING.BILLING_DATE = V_DATE.DATECOLUMNS 
AND T_CARD.CARD_ID = T_BILLING.CARD_ID 
ORDER BY DATECOLUMNS DESC;
-- V_DATE
CREATE VIEW V_DATE AS
SELECT DISTINCT "DATECOLUMNS" FROM
(
SELECT BILLING_DATE AS "DATECOLUMNS" FROM T_BILLING 
UNION
SELECT SAVING_DATE AS "DATECOLUMNS" FROM T_SAVING
);
-- V_ASSET
CREATE VIEW V_ASSET AS
SELECT ASSET_DATE AS "ASSET_DATE",ASSET_SUMSAVINGAMOUNT,ASSET_SUMBILLINGAMOUNT,IFNULL(ASSET_SUMSAVINGAMOUNT - ASSET_SUMBILLINGAMOUNT,0) AS "ASSET_AMOUNT" FROM 
(
SELECT DATECOLUMNS AS "ASSET_DATE",SUM(SAVING_AMOUNT) AS "ASSET_SUMSAVINGAMOUNT" FROM V_SAVING2 GROUP BY DATECOLUMNS
)
INNER JOIN 
(
SELECT DATECOLUMNS AS "ASSET_DATE",SUM(BILLING_AMOUNT) AS "ASSET_SUMBILLINGAMOUNT" FROM V_BILLING2 GROUP BY ASSET_DATE
)
USING (ASSET_DATE)
ORDER BY ASSET_DATE DESC;